# Generated by Django 4.2.7 on 2023-11-07 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('niveau_etude', models.CharField(max_length=255)),
                ('filiere', models.CharField(max_length=255)),
                ('matiere', models.CharField(choices=[('MATH', 'Mathématiques'), ('PHYS', 'Physique'), ('CHEM', 'Chimie'), ('BIO', 'Biologie'), ('HIST', 'Histoire'), ('GEO', 'Géographie'), ('FR', 'Français'), ('ENG', 'Anglais')], max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('date_depot', models.DateTimeField(auto_now_add=True)),
                ('contry', models.CharField(choices=[('DZ', 'Algérie'), ('AO', 'Angola'), ('BJ', 'Bénin'), ('BW', 'Botswana'), ('BF', 'Burkina Faso'), ('BI', 'Burundi'), ('CM', 'Cameroun'), ('CV', 'Cap-Vert'), ('CF', 'République centrafricaine'), ('TD', 'Tchad'), ('KM', 'Comores'), ('CG', 'Congo-Brazzaville'), ('CD', 'Congo-Kinshasa'), ('DJ', 'Djibouti'), ('EG', 'Égypte'), ('GQ', 'Guinée équatoriale'), ('ER', 'Érythrée'), ('SZ', 'Eswatini'), ('ET', 'Éthiopie'), ('GA', 'Gabon'), ('GM', 'Gambie'), ('GH', 'Ghana'), ('GN', 'Guinée'), ('CI', "Côte d'Ivoire"), ('KE', 'Kenya'), ('LS', 'Lesotho'), ('LR', 'Liberia'), ('LY', 'Libye'), ('MG', 'Madagascar'), ('MW', 'Malawi'), ('ML', 'Mali'), ('MR', 'Mauritanie'), ('MU', 'Maurice'), ('MA', 'Maroc'), ('MZ', 'Mozambique'), ('NA', 'Namibie'), ('NE', 'Niger'), ('NG', 'Nigeria'), ('UG', 'Ouganda'), ('RW', 'Rwanda'), ('ST', 'Sao Tomé-et-Principe'), ('SN', 'Sénégal'), ('SC', 'Seychelles'), ('SL', 'Sierra Leone'), ('SO', 'Somalie'), ('ZA', 'Afrique du Sud'), ('SS', 'Soudan du Sud'), ('SD', 'Soudan'), ('TZ', 'Tanzanie'), ('TG', 'Togo'), ('TN', 'Tunisie'), ('UG', 'Ouganda'), ('ZM', 'Zambie'), ('ZW', 'Zimbabwe')], max_length=255)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('fichier', models.FileField(upload_to='archives/')),
                ('type_examen', models.CharField(choices=[('1T', 'premier Trimestre'), ('2T', 'deuxieme Trimestre'), ('3T', 'troisieme trimestre'), ('BAC', 'Baccalauréat'), ('PROB', 'Probatoire'), ('UNIV', 'Université')], max_length=4)),
            ],
        ),
    ]
