# Generated by Django 4.2.7 on 2023-11-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Archive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='archive',
            old_name='author',
            new_name='ecole',
        ),
        migrations.RenameField(
            model_name='archive',
            old_name='filiere',
            new_name='examen',
        ),
        migrations.RenameField(
            model_name='archive',
            old_name='type_examen',
            new_name='niveau',
        ),
        migrations.RenameField(
            model_name='archive',
            old_name='contry',
            new_name='pays',
        ),
        migrations.RenameField(
            model_name='archive',
            old_name='niveau_etude',
            new_name='publicateur',
        ),
        migrations.RemoveField(
            model_name='archive',
            name='date_depot',
        ),
        migrations.RemoveField(
            model_name='archive',
            name='description',
        ),
        migrations.AlterField(
            model_name='archive',
            name='fichier',
            field=models.FileField(upload_to='archive_files/'),
        ),
    ]
