# Generated by Django 4.2.7 on 2023-11-07 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bursary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('partial', 'Partielle'), ('full', 'Complete')], default='', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('duration', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('total_slots', models.IntegerField(blank=True, null=True)),
                ('available_slots', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('applicants', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
