# Generated by Django 4.2.7 on 2023-11-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bourse', '0002_bursary_cover_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bursary',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
