# Generated by Django 4.2.7 on 2023-11-15 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bourse', '0003_alter_bursary_cover_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('publicateur', models.CharField(max_length=255)),
                ('categorie', models.CharField(max_length=255)),
                ('financement', models.CharField(choices=[('partial', 'Partielle'), ('full', 'Complete')], default='', max_length=50)),
                ('nature', models.CharField(choices=[('en_ligne', 'En ligne'), ('en_presentiel', 'En présentiel')], max_length=50)),
                ('lieu', models.CharField(default='', max_length=255)),
                ('niveau', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('fichier_a_joindre', models.FileField(upload_to='bourse_files/')),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('commentaire', models.TextField()),
                ('bourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bourse.bourse')),
            ],
        ),
        migrations.CreateModel(
            name='Postulant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('commentaire', models.TextField()),
                ('bourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bourse.bourse')),
            ],
        ),
        migrations.DeleteModel(
            name='Bursary',
        ),
    ]
