# Generated by Django 4.2.7 on 2023-11-17 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Bourse', '0004_bourse_commentaire_postulant_delete_bursary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentaire',
            old_name='commentaire',
            new_name='contenu',
        ),
        migrations.RenameField(
            model_name='postulant',
            old_name='commentaire',
            new_name='contenu',
        ),
        migrations.RemoveField(
            model_name='commentaire',
            name='email',
        ),
        migrations.AddField(
            model_name='commentaire',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='postulant',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='nom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
