# Generated by Django 4.2.7 on 2023-11-18 06:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='partage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='event',
            old_name='lieu',
            new_name='intervenants',
        ),
        migrations.RemoveField(
            model_name='event',
            name='lien_partage',
        ),
        migrations.RemoveField(
            model_name='event',
            name='nom',
        ),
        migrations.AddField(
            model_name='event',
            name='billet',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non')], default='oui', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='categorie',
            field=models.CharField(choices=[('se', 'EVENEMT SIMPLE'), ('vip', 'EVENEMENT VIP'), ('ecole', 'EVENEMENT SCOLAIRE'), ('dip', 'REMISE DE DIPLOME')], default='se', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='format_event',
            field=models.CharField(choices=[('prive', 'PRIVE'), ('public', 'PUBLIC')], default='prive', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='fuseau_horaire',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='event',
            name='heure_debut',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
        migrations.AddField(
            model_name='event',
            name='heure_fin',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
        migrations.AddField(
            model_name='event',
            name='type_event',
            field=models.CharField(choices=[('dip', 'DIPLOME'), ('MEET', 'REUNION')], default='dip', max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_debut',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_fin',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Participate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Event.event')),
            ],
        ),
    ]
